<?php 
include ("conexion.php");

$sql="CREATE TABLE IF NOT EXISTS CITAS (
IDCITAS INT AUTO_INCREMENT PRIMARY KEY,
FECHA DATE NOT NULL,
HORA TIME NOT NULL,
DURACION VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
ESTADOCITA ENUM('PENDIENTE','CONFIRMADA','FINALIZADA','CANCELADA') DEFAULT 'PENDIENTE',
IDEMPLEADO INT NOT NULL,
IDUSUARIO INT NOT NULL,
FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADOS(IDEMPLEADO),
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
) ENGINE=InnoDB";

if ($conn->query($sql)) {
    echo "Tabla lista";
} else {
    echo "Error: " . $conn->error;
}
?>